# Generated by Django 4.2.1 on 2023-06-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_curs', models.CharField(max_length=50)),
                ('titlu_curs', models.CharField(max_length=50)),
                ('an', models.IntegerField()),
                ('semestru', models.IntegerField()),
                ('credite', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Cursuri',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_matricol', models.CharField(max_length=20)),
                ('id_curs', models.CharField(max_length=50)),
                ('valoare', models.IntegerField()),
                ('data_notare', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Note',
            },
        ),
        migrations.CreateModel(
            name='Profesori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prof', models.CharField(max_length=50)),
                ('nume', models.CharField(max_length=50)),
                ('prenume', models.CharField(max_length=50)),
                ('grad_didactic', models.CharField(max_length=50)),
                ('id_curs', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Profesori',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_matricol', models.CharField(max_length=20)),
                ('nume', models.CharField(max_length=50)),
                ('prenume', models.CharField(max_length=50)),
                ('an', models.IntegerField()),
                ('grupa', models.CharField(max_length=2)),
                ('data_nastere', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Studenti',
            },
        ),
    ]
