# Generated by Django 4.2.1 on 2023-06-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizualizare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Optionale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pachet', models.CharField(max_length=50)),
                ('optiunea1', models.CharField(max_length=50)),
                ('optiunea2', models.CharField(max_length=50)),
                ('optiunea3', models.CharField(max_length=50)),
                ('optiunea4', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Optionale',
            },
        ),
    ]
