# Generated by Django 4.2.1 on 2023-06-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizualizare', '0002_optionale'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionale',
            name='nr_matricol',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
