# Generated by Django 4.2.1 on 2023-06-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizualizare', '0003_optionale_nr_matricol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='valoare',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
