# Generated by Django 4.2.1 on 2023-06-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizualizare', '0005_alter_note_data_notare'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='cetatenia',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='mama',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='nationalitatea',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='specializare',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='tata',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='telefon',
            field=models.IntegerField(null=True),
        ),
    ]
